# Generated by Django 5.1.4 on 2024-12-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_uuid_alter_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
    ]
