# Generated by Django 5.1.4 on 2024-12-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_created_profile_modifiyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
