# Generated by Django 5.1.4 on 2024-12-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='download.jpeg', null=True, upload_to='avaters/'),
        ),
    ]
